name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - run: pip install .
    - run: pip install pyinstaller
    - run: pyinstaller -F ./dvuploader/cli.py -n dvuploader-${{ matrix.os }} --distpath ./bin
    - name: Push
      run: |
        git add ./bin/dvuploader-${{ matrix.os }}
        git config --global user.name 'Build Bot'
        git config --global user.email 'build@bot.com'
        git commit -am "Updated CLI Binary for ${{ matrix.os }}"
        git push