name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install .
    - run: pip install pyinstaller
    - run: pyinstaller -F ./dvuploader/cli.py -n dvuploader-${{ matrix.os }}
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*